name: Sort

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true  # Required for FFmpeg installation
  API: ${{ secrets.API}}
  TOKEN: ${{ secrets.TOKEN}}
  GMAIL: ${{ secrets.GMAIL}}
  PASS: ${{ secrets.PASS}}
  AC_TOKEN: ${{ secrets.AC_TOKEN}}
  RYNX: ${{ secrets.RYNX}}
  

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Setup FFmpeg with Retry
        run: |
          RETRIES=5
          COUNT=0
          until [ $COUNT -ge $RETRIES ]
          do
            echo "Attempt $(($COUNT+1)) to install FFmpeg..."
            if curl -sL https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz | tar xJ && sudo mv ffmpeg-*-amd64-static/ffmpeg /usr/local/bin/; then
              echo "FFmpeg installed successfully."
              break
            else
              echo "FFmpeg install failed. Retrying in 5 seconds..."
              COUNT=$(($COUNT+1))
              sleep 5
            fi
          done
      
          if [ $COUNT -eq $RETRIES ]; then
            echo "FFmpeg installation failed after $RETRIES attempts."
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.2'
          
      - name: Install requirements
        run: pip install -r requirements.txt
        
      - name: Test env vars for python
        run: TEST_SECRET=${{ secrets.API}}
        
      - name: Download
        run: python download.py

      - name: Run Bot
        run: python sort_main.py
