name: Sort

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true  # Required for FFmpeg installation
  API: ${{ secrets.API}}
  TOKEN: ${{ secrets.TOKEN}}
  GMAIL: ${{ secrets.GMAIL}}
  PASS: ${{ secrets.PASS}}
  AC_TOKEN: ${{ secrets.AC_TOKEN}}
  RYNX: ${{ secrets.RYNX}}
  

jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v3
        
      - name: Setup FFmpeg with Retry (Safe)
        run: |
          RETRIES=5
          COUNT=0
          SUCCESS=0
          until [ $COUNT -ge $RETRIES ]; do
            echo "Attempt $(($COUNT+1)) to install FFmpeg..."
            wget -q -O ffmpeg.tar.xz https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
            if file ffmpeg.tar.xz | grep -q "XZ compressed data"; then
              tar -xf ffmpeg.tar.xz
              sudo mv ffmpeg-*-amd64-static/ffmpeg /usr/local/bin/
              ffmpeg -version && SUCCESS=1 && echo "FFmpeg installed successfully." && break
            else
              echo "Download failed or file is invalid. Retrying in 5 seconds..."
            fi
            COUNT=$(($COUNT+1))
            sleep 5
          done
      
          if [ $SUCCESS -ne 1 ]; then
            echo "FFmpeg installation failed after $RETRIES attempts."
            exit 1
          fi


      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.2'
          
      - name: Install requirements
        run: pip install -r requirements.txt
        
      - name: Test env vars for python
        run: TEST_SECRET=${{ secrets.API}}
        
      - name: Download
        run: python download.py

      - name: Run Bot
        run: python sort_main.py
